"""tables

Revision ID: 20c5a25cfacb
Revises: 3b8dcb0b4d7a
Create Date: 2023-04-18 03:34:07.999661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c5a25cfacb'
down_revision = '3b8dcb0b4d7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deck', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('deck')

    # ### end Alembic commands ###
