"""tables

Revision ID: 2d055e97ccd6
Revises: 043cb3b153f2
Create Date: 2023-04-18 00:58:56.012364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d055e97ccd6'
down_revision = '043cb3b153f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funds', sa.Integer(), nullable=True))
        batch_op.drop_column('setFunds')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setFunds', sa.INTEGER(), nullable=True))
        batch_op.drop_column('funds')

    # ### end Alembic commands ###
