"""tables

Revision ID: 3436532bcc7a
Revises: 20c5a25cfacb
Create Date: 2023-04-18 10:47:33.279747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3436532bcc7a'
down_revision = '20c5a25cfacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('betAmount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('funds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('funds')
        batch_op.drop_column('betAmount')

    # ### end Alembic commands ###
