"""tables

Revision ID: 3b8dcb0b4d7a
Revises: 2d055e97ccd6
Create Date: 2023-04-18 01:28:03.794613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b8dcb0b4d7a'
down_revision = '2d055e97ccd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gameStart', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('gameStart')

    # ### end Alembic commands ###
