"""tables

Revision ID: ef22f380a50b
Revises: aaab7d0915a8
Create Date: 2023-04-20 00:07:34.052403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef22f380a50b'
down_revision = 'aaab7d0915a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('deck')
        batch_op.drop_column('gameStart')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gameStart', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deck', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
